### ISSUE TITLE
Is there a way to generate guard with no export?

### ISSUE THREAD

**Issue by changwoolab** [rhys-vdw/ts-auto-guard#221]
I could generate guard file if I write code with export.

```ts
export interface ~~ { }
```

But I could not make guard file if I didn't export it.

```ts
interface ~~ { }
```

Is there any way to generate guard without export?

**Comment by download13** [comment]
The guard function needs to refer to the type for its `param is Type` return type. How would it do that if the type is not exported?

You can't do this while manually writing a guard file, so I don't see how a library could do it.

Unless you want a guard written into an existing file instead of being written into a separate file. That seems like there's more risk of damaging an existing code file.
I'm not necessarily opposed to it as a feature. ts-morph can pretty safely modify existing files, and version control minimizes the risk of catastrophic mistakes, but that's not something this library has ever done as far as I know.

I'm curious what you're trying to do. Is there a reason you can't export your type?

**Comment by changwoolab** [comment]
I thought that I could manage codes more efficiently if I manage types in the same file.
But I decided to split types into separate files. So it doesn't matter now. :)
