### ISSUE TITLE
Deploy workflow published version 5 without committing changes

### ISSUE THREAD

**Issue by dls314** [rhys-vdw/ts-auto-guard#258]
Hi, I noticed that https://www.npmjs.com/package/ts-auto-guard/v/5.0.0 is published, but I don't see any related changes here yet and wanted to ask for confirmation that the release is intended. Thanks!

**Comment by rhys-vdw** [comment]
Ahhh... Thanks. I was wondering if that happened. Yes, the publish script ran but failed to commit at the end due to some expired token issue.

https://github.com/rhys-vdw/ts-auto-guard/actions/runs/9476033112

TODO:
- [ ] Manually updating the package version and tagging that commit (since that's all the workflow does).
- [ ] Fix deploy token.

Would be nice to be able to get the git merge to fail the workflow before the deploy succeeds, but I think npm does the bump + tag in the same step at which it deploys.

**Comment by rhys-vdw** [comment]
The error:

```
git push --follow-tags
  shell: /usr/bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    github-token: ***
remote: Permission to rhys-vdw/ts-auto-guard.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/rhys-vdw/ts-auto-guard/': The requested URL returned error: 40[3](https://github.com/rhys-vdw/ts-auto-guard/actions/runs/9476033112/job/26108298911#step:11:3)
Error: Process completed with exit code 128.
```

Hm, so we have this in the workflow:

https://github.com/rhys-vdw/ts-auto-guard/blob/cfc2fd0262bedd9d4a1636ce6d7df0d5655988b7/.github/workflows/cd.yml#L37-L39

And I've given the workflow has read/write permissions and is using the correct token.

![image](https://github.com/rhys-vdw/ts-auto-guard/assets/822105/1764eb41-44eb-4120-a647-a22ed1bbf109)

Actually not sure what is going wrong here. It has always worked in the past.

**Comment by rhys-vdw** [comment]
Ah, worked it out:

https://github.com/rhys-vdw/ts-auto-guard/blob/cfc2fd0262bedd9d4a1636ce6d7df0d5655988b7/.github/workflows/cd.yml#L18-L20

This should be `contents: read`. I guess this overrides the repo-wide setting.

**Comment by elliot-huffman** [comment]
I would like to suggest that we start using the [GitHub releases system](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) so that we can track a changelog and when a new release is published that we trigger the NPM deployment (like how my package publishes: https://github.com/Software-Hardware-Integration-Lab/ObjectID-Converter/blob/main/.github/workflows/NPM-Publish.yml).
This means that a manual commit will be needed to bump the package and lock file version, but I personally don't mind that myself, unless you prefer to not do that.

**Comment by rhys-vdw** [comment]
@elliot-huffman I am basically at full capacity running my company, which does not use this project, so I'm more than happy for you to take the initiative if and while you're inspired to do so!

**Comment by elliot-huffman** [comment]
Can do, I just don't have package access to do the token stuff, but I can overhaul the publish action to work automatically and stabily.

**Comment by elliot-huffman** [comment]
Just updated the publish pipeline and synced it with the NPM system.
I set up the GitHub releases system to keep track of the releases on our side with a change log as well as a check to prevent publishing to NPM if the pre-reqs aren't met.

The fix for this was the release of [5.0.1](https://github.com/rhys-vdw/ts-auto-guard/releases/tag/5.0.1), please see the changelog for more details :)

**Comment by rhys-vdw** [comment]
Amazing work, @elliot-huffman. 🎉

**Comment by rhys-vdw** [comment]
> The fix for this was the release of [5.0.1](https://github.com/rhys-vdw/ts-auto-guard/releases/tag/5.0.1), please see the changelog for more details :)

Seems we don't have a git tag for 5.0.1. We should potentially branch from https://github.com/rhys-vdw/ts-auto-guard/commit/ba25d264bc0e5d7058318dd896a30d34067eae32 to create a 5.0.0 tag too.

**Comment by rhys-vdw** [comment]
My mistake, they are there, but no longer prefixed with `v` so they're sorted to the bottom. Fine with it.

**Comment by elliot-huffman** [comment]
I will make a wiki page on how the new automated publishing system works and how the input validation checks the tag info in the publish workflow.
This will reduce confusion for future releases.
Sorry about that!

**Comment by rhys-vdw** [comment]
@elliot-huffman nah nothing to apologize for, I was just a bit hasty to comment. Wiki is welcome if you would like to do it, otherwise I don't think it is required.
