### ISSUE TITLE
optional props check and tsconfig.json with references array

### ISSUE THREAD

**Issue by GuilhermeScotti** [rhys-vdw/ts-auto-guard#317]
I was missing `"strictNullChecks": true` in `compilerOptions` and noticed checks like `typeof typedObj.theType === "undefined" || ...` for optional? props would still not be generated in this scenario:

For a web project I had Vite generated tsconfig.json setup like so:

```json
{
"files": [],
  "references": [
    { "path": "./tsconfig.app.json" }, //for app files, e.g. under /src
    { "path": "./tsconfig.node.json" } //for vite.config.ts 
  ]
}
```

If I add `"strictNullChecks": true` to `tsconfig.app.json` (or both) it would still not generate the expected validation code.
But if I completely replace `tsconfig.json` with `tsconfig.app.json`, thus having `"strictNullChecks": true` in `tsconfig.json` it generates the `undefined` check.

Maybe I missed something, but is this expected?

Unrelated note: in my global eslint config I had to add under `project:[]` both `tsconfig.node.json` and `tsconfig.app.json`. Similarly just `tsconfig.json` would not work.

**Comment by rhys-vdw** [comment]
I have never disabled strict null checks, I know that it will cause the library to generate useless type assertions, but they are (as far as I understand) correct. This is because without null checks you are essentially saying that every field in optional.

You can use the `--project` option to specify the path to the `tsconfig.json` you would like to use. Just make a normal tsconfig with strict enabled.

I don't really understand your scenario otherwise. You need to give specifics wrt "expected validation code" and "props would still not be generated".

**Comment by GuilhermeScotti** [comment]
Oh totally! `"strictNullChecks": true` was disabled by mistake on my project.

Ah ok, got it I can use `--project`. Thanks.

Sorry it was not well specified:

`expected validation code`:  meant the code that checks for `undefined` for optional props.
`props would still not be generated`: meant (the checks) for optional props would still not be generated

I meant the scenario is a main tsconfig.json file that actually just references other tsconfig.specific.json files.

Hope it's more clear now. But `--project` would work on my case. Thanks!

**Comment by rhys-vdw** [comment]
Okay, cool. I think I'll close this one then. Glad you found your solution!
